import type { Artifact, SearchableArtifact } from "./types";

// Loads the real marketplace index generated by scripts/build-index.mjs
// (site/index.json) at runtime. See Docs/SITE-SPEC.md.
//
// The relative "../index.json" resolves correctly in both environments:
// - dev: browser/public/index.json is synced there by `npm run predev`,
//   served at the Vite dev server root, so "../index.json" collapses to "/index.json".
// - prod: the app is published at <pages-url>/browser/, one level below
//   site/index.json, so "../index.json" reaches it directly.
const INDEX_URL = "../index.json";

interface SiteIndex {
  marketplace: string;
  generatedAt: string;
  artifacts: Artifact[];
}

function withHaystack(a: Artifact): SearchableArtifact {
  const bodyText = a.blocks
    .map((b) => b.text)
    .join(" ")
    .toLowerCase();
  return {
    ...a,
    haystack: {
      name: `${a.name} ${a.displayName}`.toLowerCase(),
      desc: a.description.toLowerCase(),
      body: bodyText,
    },
  };
}

export async function loadIndex(): Promise<SearchableArtifact[]> {
  const res = await fetch(INDEX_URL);
  if (!res.ok) {
    throw new Error(`Failed to load marketplace index: ${res.status} ${res.statusText}`);
  }
  const data: SiteIndex = await res.json();
  return data.artifacts.map(withHaystack);
}
